---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nautilus
  template:
    metadata:
      labels:
        app: nautilus
    spec:
      containers:
        - name: nautilus
          image: docker.io/dswg/nautilus
          ports:
            - containerPort: 3030
